# markdownlint configuration
# https://github.com/DavidAnson/markdownlint

# Default: all rules enabled
default: true

# MD003 - Heading style
# Use ATX style (#)
MD003:
  style: atx

# MD004 - Unordered list style
# Use dashes
MD004:
  style: dash

# MD007 - Unordered list indentation
MD007:
  indent: 2

# MD009 - Trailing spaces
# Allow 2 trailing spaces (line break)
MD009:
  br_spaces: 2

# MD010 - Hard tabs
MD010:
  code_blocks: false

# MD012 - Multiple consecutive blank lines
MD012:
  maximum: 1

# MD013 - Line length
# Disabled - long lines common with URLs, tables, code
MD013: false

# MD022 - Headings should be surrounded by blank lines
MD022:
  lines_above: 1
  lines_below: 1

# MD024 - Multiple headings with same content
# Allow in different sections
MD024:
  siblings_only: true

# MD025 - Single top-level heading
MD025:
  front_matter_title: ""

# MD026 - Trailing punctuation in heading
MD026:
  punctuation: ".,;:!"

# MD029 - Ordered list item prefix
# Use ordered numbers (1. 2. 3.)
MD029:
  style: ordered

# MD030 - Spaces after list markers
MD030:
  ul_single: 1
  ol_single: 1
  ul_multi: 1
  ol_multi: 1

# MD031 - Fenced code blocks should be surrounded by blank lines
MD031:
  list_items: true

# MD032 - Lists should be surrounded by blank lines
MD032: true

# MD033 - Inline HTML
# Disabled - HTML sometimes needed for formatting
MD033: false

# MD034 - Bare URLs
# Disabled - bare URLs are fine in docs
MD034: false

# MD035 - Horizontal rule style
MD035:
  style: "---"

# MD036 - Emphasis used instead of heading
MD036: false

# MD040 - Fenced code blocks should have a language
# Disabled - not all code blocks need language (output, pseudocode)
MD040: false

# MD041 - First line should be top-level heading
# Disabled - files may start with frontmatter
MD041: false

# MD044 - Proper names should have correct capitalization
MD044:
  names: []
  code_blocks: false

# MD045 - Images should have alt text
MD045: true

# MD046 - Code block style
# Use fenced (```)
MD046:
  style: fenced

# MD047 - Files should end with single newline
MD047: true

# MD048 - Code fence style
# Use backticks
MD048:
  style: backtick

# MD049 - Emphasis style
# Use asterisks for emphasis
MD049:
  style: asterisk

# MD050 - Strong style
# Use asterisks for bold
MD050:
  style: asterisk
