# Sourcery configuration
# https://docs.sourcery.ai/Reference/Configuration/sourcery-yaml/

version: '1'

ignore:
  - .git
  - .venv
  - __pycache__
  - .pytest_cache
  - .ruff_cache
  - .mypy_cache
  - htmlcov
  - dist
  - build
  - "*.egg-info"

rule_settings:
  enable:
    - default
    - no-long-functions  # Flag functions > 50 lines
  python_version: '3.14'
  rule_types:
    - refactoring
    - suggestion
    - comment
